### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by jefferis** [jefferislab/LHlibrary#3]
When I click on the Download All Data button, it shows a little modal window. When I click download on that, it  pauses for a bit and then eventually gives me a 404 not found error. Can you get the app to download?

I think we need to provide a simpler mechanism for this download on a dedicated tab or page of its own

![image](https://user-images.githubusercontent.com/23763/55712046-e7a14700-59e5-11e9-940d-ef44c3485744.png)

**Comment by alexanderbates** [comment]
Okay, I shall investigate this and also add a downloads page, hopefully before I travel to Berlin

**Comment by alexanderbates** [comment]
I have added a downloads tab, that allows you to download morphologies, odour response data, and some summary data on LHNs, PNs and the split lines. Download should now be working.

**Comment by jefferis** [comment]
Downloads tab looks good. Thanks!

How many neurons are you expecting when downloading all morphologies? This is what I see: 

![image](https://user-images.githubusercontent.com/23763/55839279-3999b800-5b1f-11e9-8562-ee7c438e33f7.png)

Seems to me there should be more!

**Comment by jefferis** [comment]
OK, I get it. These are just the dye fills.

https://github.com/jefferislab/LHlibrary/blob/722b49887b16c2b69f3f477739c70e6e658daeaf/server.R#L595-L598

Still it seems to me that we need to provide a download of *all* the morphologies with associated metadata. This can be a static download e.g. at http://flybrain.mrc-lmb.cam.ac.uk/dokuwiki/doku.php?id=si:frechter2018:start but it should be available.

**Comment by alexanderbates** [comment]
This was a mistake, I downloaded a subset for testing at first. Rectified, now all morphologies can now be downloaded
